In [1]:
from pynq import Overlay, GPIO, Register, allocate, MMIO
import os
import numpy as np
from convert import *
import struct
converter=Converter()

In [2]:
overlay = Overlay("conv_test.bit")
convip=overlay.conv_combined_0
inputip=overlay.InputLayer_0
outputip=overlay.OutputLayer_0

In [3]:
convip.register_map

RegisterMap {
  CTRL = Register(AP_START=0, AP_DONE=0, AP_IDLE=1, AP_READY=0, RESERVED_1=0, AUTO_RESTART=0, RESERVED_2=0),
  GIER = Register(Enable=0, RESERVED=0),
  IP_IER = Register(CHAN0_INT_EN=0, CHAN1_INT_EN=0, RESERVED=0),
  IP_ISR = Register(CHAN0_INT_ST=0, CHAN1_INT_ST=0, RESERVED=0),
  wt = Register(wt=0),
  dwt = Register(dwt=0),
  b = Register(b=0),
  db = Register(db=0),
  F = Register(F=0),
  C = Register(C=0),
  H = Register(H=0),
  W = Register(W=0),
  FH = Register(FH=0),
  FW = Register(FW=0),
  fwprop = Register(fwprop=0, RESERVED=0)
}

In [4]:
xbuff=allocate(shape=(4,),dtype='uint16')
wbuff=allocate(shape=(2,),dtype='uint16')
bbuff=allocate(shape=(3,),dtype='uint16')
ybuff=allocate(shape=(3,),dtype='uint16')

In [5]:
x=[int(converter.encode(0.1)),int(converter.encode(0.1)),int(converter.encode(0.1)),int(converter.encode(0.1))]
xbuff[:]=x[:]
xbuff.flush()

In [6]:
inputip.register_map.x=xbuff.physical_address
inputip.register_map.dim=4
inputip.register_map.ddrtobram=1

In [7]:
inputip.write(0x00,1)

In [12]:
w=[int(converter.encode(1.0)),int(converter.encode(1.0))]
b=[int(converter.encode(0)),int(converter.encode(0)),int(converter.encode(0))]


In [13]:
wbuff[:]=w[:]
bbuff[:]=b[:]

wbuff.flush()
bbuff.flush()

In [14]:
convip.register_map.wt=wbuff.physical_address
convip.register_map.b=bbuff.physical_address
convip.register_map.F=1
convip.register_map.C=1
convip.register_map.H=4
convip.register_map.W=1
convip.register_map.FH=2
convip.register_map.FW=1

convip.register_map.fwprop=1

In [15]:
convip.register_map

RegisterMap {
  CTRL = Register(AP_START=0, AP_DONE=0, AP_IDLE=1, AP_READY=0, RESERVED_1=0, AUTO_RESTART=0, RESERVED_2=0),
  GIER = Register(Enable=0, RESERVED=0),
  IP_IER = Register(CHAN0_INT_EN=0, CHAN1_INT_EN=0, RESERVED=0),
  IP_ISR = Register(CHAN0_INT_ST=0, CHAN1_INT_ST=0, RESERVED=0),
  wt = Register(wt=377790464),
  dwt = Register(dwt=0),
  b = Register(b=377794560),
  db = Register(db=0),
  F = Register(F=1),
  C = Register(C=1),
  H = Register(H=4),
  W = Register(W=1),
  FH = Register(FH=2),
  FW = Register(FW=1),
  fwprop = Register(fwprop=1, RESERVED=0)
}

In [16]:
convip.write(0x00,1)

In [17]:
outputip.register_map.y=ybuff.physical_address
outputip.register_map.dim=3
outputip.register_map.ddrtobram=0

In [18]:
outputip.write(0x00,1)

In [19]:
outputip.register_map

RegisterMap {
  CTRL = Register(AP_START=0, AP_DONE=0, AP_IDLE=1, AP_READY=0, RESERVED_1=0, AUTO_RESTART=0, RESERVED_2=0),
  GIER = Register(Enable=0, RESERVED=0),
  IP_IER = Register(CHAN0_INT_EN=0, CHAN1_INT_EN=0, RESERVED=0),
  IP_ISR = Register(CHAN0_INT_ST=0, CHAN1_INT_ST=0, RESERVED=0),
  y = Register(y=377798656),
  dy = Register(dy=0),
  dim = Register(dim=3),
  ddrtobram = Register(ddrtobram=0, RESERVED=0)
}

In [21]:
ybuff.invalidate()
print(ybuff)

for i in range(3):
    print(converter.decode(int(ybuff[i])))

[ 0 12 24]
[0.]
[0.09375]
[0.1875]


In [52]:
x=[1,2,3,4]
x1=allocate(shape=(4,),dtype='uint16')
x2=allocate(shape=(4,),dtype='uint16')

for i in range(4):
    x1[i]= x[i]

In [53]:
inputip.register_map.x=x1.physical_address
inputip.register_map.dim=4
inputip.register_map.ddrtobram=1

inputip.write(0x00,1)

In [57]:
inputip.register_map.x=x2.physical_address
inputip.register_map.dim=4
inputip.register_map.ddrtobram=0

inputip.write(0x00,1)

In [58]:
print(x2)

[4 1 2 3]


In [54]:
print(x1)

[1 2 3 4]


In [38]:
outputip.register_map

RegisterMap {
  CTRL = Register(AP_START=0, AP_DONE=0, AP_IDLE=1, AP_READY=0, RESERVED_1=0, AUTO_RESTART=0, RESERVED_2=0),
  GIER = Register(Enable=0, RESERVED=0),
  IP_IER = Register(CHAN0_INT_EN=0, CHAN1_INT_EN=0, RESERVED=0),
  IP_ISR = Register(CHAN0_INT_ST=0, CHAN1_INT_ST=0, RESERVED=0),
  y = Register(y=377806848),
  dy = Register(dy=0),
  dim = Register(dim=4),
  ddrtobram = Register(ddrtobram=1, RESERVED=0)
}